version: '3'

services:
  web:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/etc/nginx/html/static
    ports:
      - "80:80"

volumes:
    static_volume: